schedules:
  news_sites:
    interval: "*/30 * * * *"  # Every 30 minutes
    sources:
      - name: "major_news"
        urls: ["url1", "url2"]
        scraper_type: "static"
  
  social_media:
    interval: "0 */2 * * *"   # Every 2 hours
    sources:
      - name: "twitter"
        api_endpoint: "api_url"
        scraper_type: "api"
  
  blogs:
    interval: "0 */4 * * *"   # Every 4 hours
    sources:
      - name: "tech_blogs"
        urls: ["blog1", "blog2"]
        scraper_type: "dynamic"

error_handling:
  max_retries: 3
  retry_delay: 300  # seconds
  alert_threshold: 5  # number of failures before alerting 