# Prometheus Settings
prometheus:
  port: 9090
  metrics_path: "/metrics"
  scrape_interval: 15s

# Grafana Settings
grafana:
  port: 3000
  admin_password: "${GRAFANA_PASSWORD}"
  datasources:
    - name: "Prometheus"
      type: "prometheus"
      url: "http://localhost:9090"

# Logging
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/scraper.log"
