name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
    paths:
      - 'projects/scraper/applications/facebook-scraper/**'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'projects/scraper/applications/facebook-scraper/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: projects/scraper/applications/facebook-scraper

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          pip install -e .
          
      - name: Create directory structure
        run: |
          mkdir -p src/scraper
          mkdir -p src/pipeline
          mkdir -p tests
          
      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}/projects/scraper/applications/facebook-scraper
        run: |
          pytest tests/ -v --cov=src

  docker:
    needs: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: projects/scraper/applications/facebook-scraper 