apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-framework
spec:
  replicas: 3
  selector:
    matchLabels:
      app: data-framework
  template:
    metadata:
      labels:
        app: data-framework
    spec:
      containers:
      - name: scraper
        image: data-framework:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: ENVIRONMENT
          value: "production"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
