version: '3.8'

services:
  scraper:
    build: .
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"
      - "9090:9090"
    environment:
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    volumes:
      - ./config/prometheus:/etc/prometheus
    ports:
      - "9090:9090"
    depends_on:
      - scraper

  grafana:
    image: grafana/grafana
    volumes:
      - ./config/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
