mongodb:
  collections:
    training_data:
      - text_corpus
      - market_data
      - social_content
    model_outputs:
      - embeddings
      - predictions
      - intermediate_results

sql:
  tables:
    metrics:
      - model_performance
      - validation_results
    structured_data:
      - market_metrics
      - user_interactions 